services:
  postgres:
    image: postgres:latest
    container_name: sales-audit-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales-audit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - JWT_SECRET=${JWT_SECRET}
    container_name: sales-audit-server
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/sales-audit
      NODE_ENV: production
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: sales-audit-client
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: production
  #   env_file:
  #     - .env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
